# Generated by Django 3.2.7 on 2021-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Washirika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_kamili', models.CharField(max_length=100)),
                ('namba_ya_simu', models.IntegerField(max_length=10)),
                ('anapoishi', models.CharField(max_length=50)),
                ('jinsia', models.BooleanField(choices=[('Me', 'Mwanaume'), ('Ke', 'Mwanamke')])),
                ('amebatizwa', models.BooleanField(choices=[('N', 'Ndiyo'), ('H', 'hapana')])),
                ('kaokolewa_ggh', models.BooleanField(choices=[('N', 'Ndiyo'), ('H', 'hapana')])),
            ],
        ),
    ]
