# Generated by Django 3.2.7 on 2021-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washirika',
            name='amebatizwa',
            field=models.BooleanField(choices=[('N', 'Ndiyo'), ('H', 'Hapana')]),
        ),
        migrations.AlterField(
            model_name='washirika',
            name='kaokolewa_ggh',
            field=models.BooleanField(choices=[('N', 'Ndiyo'), ('H', 'Hapana')]),
        ),
    ]
