# Generated by Django 3.2.7 on 2021-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0003_auto_20211030_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washirika',
            name='amebatizwa',
            field=models.CharField(choices=[('N', 'Ndiyo'), ('H', 'Hapana')], max_length=1),
        ),
        migrations.AlterField(
            model_name='washirika',
            name='kaokolewa_ggh',
            field=models.CharField(choices=[('N', 'Ndiyo'), ('H', 'Hapana')], max_length=1),
        ),
    ]
