# Generated by Django 3.2.7 on 2021-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0005_vitu_vya_dhamani_vyombo_vya_mziki_na_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vifaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('gitaa', models.IntegerField()),
                ('drams', models.IntegerField()),
                ('microphone', models.IntegerField()),
                ('speaker', models.IntegerField()),
                ('vinanda', models.IntegerField()),
                ('viti', models.IntegerField()),
                ('meza', models.IntegerField()),
                ('stuli', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Vitu_vya_dhamani',
        ),
        migrations.DeleteModel(
            name='Vyombo_vya_mziki_na_IT',
        ),
    ]
