# Generated by Django 3.2.7 on 2021-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0006_auto_20211104_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('guitars', models.IntegerField()),
                ('drums', models.IntegerField()),
                ('microphones', models.IntegerField()),
                ('speakers', models.IntegerField()),
                ('keyboards', models.IntegerField()),
                ('chairs', models.IntegerField()),
                ('tables', models.IntegerField()),
                ('stools', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('physical_address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('baptised', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('rescued_ggh', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Vifaa',
        ),
        migrations.DeleteModel(
            name='Washirika',
        ),
    ]
