# Generated by Django 3.2.7 on 2021-12-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0008_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
