# Generated by Django 3.2.7 on 2021-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGH', '0009_auto_20211201_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Event', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
